CREATE TABLE game_session
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id  BIGINT,
    winner_id BIGINT,
    name      VARCHAR(255),
    CONSTRAINT pk_gamesession PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE uzer
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_uzer PRIMARY KEY (id)
);

CREATE TABLE uzer_roles
(
    user_id  BIGINT NOT NULL,
    roles_id BIGINT NOT NULL,
    CONSTRAINT pk_uzer_roles PRIMARY KEY (user_id, roles_id)
);

ALTER TABLE game_session
    ADD CONSTRAINT FK_GAMESESSION_ON_OWNER FOREIGN KEY (owner_id) REFERENCES uzer (id);

ALTER TABLE game_session
    ADD CONSTRAINT FK_GAMESESSION_ON_WINNER FOREIGN KEY (winner_id) REFERENCES uzer (id);

ALTER TABLE uzer_roles
    ADD CONSTRAINT fk_uzerol_on_role FOREIGN KEY (roles_id) REFERENCES role (id);

ALTER TABLE uzer_roles
    ADD CONSTRAINT fk_uzerol_on_user FOREIGN KEY (user_id) REFERENCES uzer (id);